### ISSUE TITLE
How to automated "refresh_token" vaulting

### ISSUE THREAD

**Issue by baumannalexj** [bespoken/GuessThePrice#11]
How do you automate your vaulting of your cli_config `refresh_token`? 
We encrypt our cli_config, and is used after Travis CI decrypts it. If it has expired, a new one is generated, but it's lost on the VM filesystem.

I'm trying to avoid:
```
ask deploy
if (cli_config has changed) {
    travis encrypt
    push to remote storage
}
```
If I did get the above to work, then we could have race conditions for feature builds

**Comment by jkelvie** [comment]
Sorry, I just saw this - but we basically get a new access token every time - we store the refresh token as an environment variable, and then create the cli config anew in the build environment every time it is run. This will automatically refresh the access token.

You can see the file that we replace the environment variables into here:
https://github.com/bespoken/GuessThePrice/blob/master/conf/ask_cli.json

**Comment by baumannalexj** [comment]
Thanks!
